/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cec;
import Entidades.Usuario;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JTextField;

/**
 *
 * @author msosa
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
     Main main = new Main();

    private boolean ingresoCorrecto = false;

    public boolean isIngresoCorrecto() {
        return ingresoCorrecto;
    }

    public void setIngresoCorrecto(boolean ingresoCorrecto) {
        this.ingresoCorrecto = ingresoCorrecto;
    }

    
    
    
    
    
    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(this);
         try {
            Web_Settings web = new Web_Settings();
            this.fieldIp.setText(web.getIp());
        } catch (IOException ex) {
            Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Usuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fieldUser = new javax.swing.JTextField();
        jL_Usuario1 = new javax.swing.JLabel();
        jPass = new javax.swing.JPasswordField();
        fieldIp = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jL_Usuario2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_Usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jL_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        jL_Usuario.setText("IP:");
        getContentPane().add(jL_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 80, 20));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 70, 30));

        fieldUser.setBackground(new java.awt.Color(51, 51, 51));
        fieldUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldUser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(fieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 270, -1));

        jL_Usuario1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jL_Usuario1.setForeground(new java.awt.Color(255, 255, 255));
        jL_Usuario1.setText("Usuario:");
        getContentPane().add(jL_Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 80, 20));

        jPass.setBackground(new java.awt.Color(51, 51, 51));
        jPass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPass.setForeground(new java.awt.Color(255, 255, 255));
        jPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassActionPerformed(evt);
            }
        });
        getContentPane().add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 270, -1));

        fieldIp.setBackground(new java.awt.Color(51, 51, 51));
        fieldIp.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        fieldIp.setForeground(new java.awt.Color(255, 255, 255));
        fieldIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIpActionPerformed(evt);
            }
        });
        getContentPane().add(fieldIp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 120, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 130, 30));

        jL_Usuario2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jL_Usuario2.setForeground(new java.awt.Color(255, 255, 255));
        jL_Usuario2.setText("Contraseña:");
        getContentPane().add(jL_Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 100, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/galaxia.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 452, 574));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassActionPerformed

    private void fieldIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ResultSet rs;
        Connection conn = null;
        JavaPostgreSQL conexion = new JavaPostgreSQL();

        if (this.fieldIp.getText().equals("test")) {
            Usuario current_user = new Usuario();
            current_user.setNombre_fantasia("test");
            current_user.setId(1);
            main.setCurrent_user(current_user);

            main.setVisible(true);
            this.setVisible(false);
        } else {
            try {
                conn = conexion.getConnection();
                Statement st = conn.createStatement();
                String consulta = "SELECT * FROM usuarios WHERE nombre = '" + this.fieldUser.getText() + "';";
                rs = st.executeQuery(consulta);
                String pass = new String();
                conn.close();
                int id_usuario = 0;
                while (rs.next()) {
                    pass = rs.getString("contrasena");
                   
                    String myPass=String.valueOf(jPass.getPassword());
                    if (myPass.equals(pass)) {
                        this.ingresoCorrecto = true;
                        id_usuario = rs.getInt("id");

                    }
                }
                st.close();
                rs.close();

                if (this.ingresoCorrecto) {
                    Usuario current_user = new Usuario();
                    current_user.setNombre_fantasia(this.fieldUser.getText());
                    current_user.setId(id_usuario);
                    main.setCurrent_user(current_user);

                    main.setVisible(true);
                    main.setLocationRelativeTo(null);
                    this.setVisible(false);

                }

            } catch (SQLException ex) {
                Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);

            } catch (IOException ex) {
                Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldIp;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jL_Usuario;
    private javax.swing.JLabel jL_Usuario1;
    private javax.swing.JLabel jL_Usuario2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPass;
    // End of variables declaration//GEN-END:variables
}
