/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inputs;

import Entidades.Recorridos;
import Entidades.Usuario;
import cec.Tabla;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.CD;

/**
 *
 * @author Programación 2
 */
public class Input_Recorridos extends javax.swing.JFrame {
    
    /**
     * Creates new form Input_Usuarios
     */
    public Input_Recorridos() {
        initComponents();
    }
    private boolean NewRecord = true;
    private int id_local = 0;

    public void Alta() throws SQLException {
        int id = Tabla.UltimoNumero("recorridos");
        jTId_cobrador.setVisible(false);
        jTId_cobrador.setText("1");
    }

    public void Modificacion(int selectedId) throws SQLException {
        
        NewRecord = false;
        id_local = selectedId;
        ResultSet rs = Tabla.select("recorridos", "id = " + selectedId);
        rs.next();
        jTDescripcion.setText(rs.getString("nombre"));
        jTId_cobrador.setText(String.valueOf(rs.getInt("id_cobrador")));
        jTId_cobrador.setVisible(false);
    }

    public void Baja() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanelRecorridos = new javax.swing.JPanel();
        jTDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jB_Guardar_Usuario = new javax.swing.JButton();
        jB_Cancelar_Usuario = new javax.swing.JButton();
        jTCobrador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCAnulado = new javax.swing.JCheckBox();
        jTId_cobrador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDescripcionActionPerformed(evt);
            }
        });

        jLabel1.setText("Descripción:");

        jB_Guardar_Usuario.setText("Guardar");
        jB_Guardar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Guardar_UsuarioActionPerformed(evt);
            }
        });

        jB_Cancelar_Usuario.setText("Cancelar");

        jTCobrador.setName("jTCobrador"); // NOI18N
        jTCobrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCobradorActionPerformed(evt);
            }
        });

        jLabel6.setText("Cobrador:");

        jLabel7.setText("Anulado:");

        jCAnulado.setText("jCheckBox1");

        jTId_cobrador.setEditable(false);
        jTId_cobrador.setName("jTCobrador"); // NOI18N
        jTId_cobrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTId_cobradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRecorridosLayout = new javax.swing.GroupLayout(jPanelRecorridos);
        jPanelRecorridos.setLayout(jPanelRecorridosLayout);
        jPanelRecorridosLayout.setHorizontalGroup(
            jPanelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecorridosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRecorridosLayout.createSequentialGroup()
                        .addGroup(jPanelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                    .addGroup(jPanelRecorridosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTId_cobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGroup(jPanelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRecorridosLayout.createSequentialGroup()
                        .addComponent(jTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(332, 332, 332)
                        .addComponent(jB_Guardar_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB_Cancelar_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCAnulado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanelRecorridosLayout.setVerticalGroup(
            jPanelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRecorridosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Guardar_Usuario)
                    .addComponent(jB_Cancelar_Usuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTId_cobrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCAnulado))
                .addGap(599, 599, 599))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRecorridos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRecorridos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDescripcionActionPerformed

    private void jB_Guardar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Guardar_UsuarioActionPerformed
        // TODO add your handling code here:

        if (NewRecord) {
            Recorridos.insert(Tabla.UltimoNumero("recorridos") + 1, jTDescripcion.getText(), Integer.parseInt(jTId_cobrador.getText()), jCAnulado.isSelected());
            this.dispose();
        } else {
            Recorridos.updateAll(id_local, jTDescripcion.getText(), Integer.parseInt(jTId_cobrador.getText()), jCAnulado.isSelected());
            this.dispose();
        }


    }//GEN-LAST:event_jB_Guardar_UsuarioActionPerformed

    private void jTCobradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCobradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCobradorActionPerformed

    private void jTId_cobradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTId_cobradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTId_cobradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_Recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_Recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_Recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_Recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_Recorridos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cancelar_Usuario;
    private javax.swing.JButton jB_Guardar_Usuario;
    private javax.swing.JCheckBox jCAnulado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTCobrador;
    private javax.swing.JTextField jTDescripcion;
    private javax.swing.JTextField jTId_cobrador;
    // End of variables declaration//GEN-END:variables

}
