/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inputs;

import cec.Tabla;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import sun.util.calendar.CalendarUtils;
import util.CD;
import util.Help;

/**
 *
 * @author Programación 2
 */
public class Input_Items extends javax.swing.JFrame {

    /**
     * Creates new form Input_Items
     */
    public Input_Items() throws SQLException {
        initComponents();

        ayudaProducto.Autocompletar(jT_Producto, "descripcion", "productos");
        NumberFormat amountFormat = NumberFormat.getNumberInstance();
        /*JFormattedTextField jF_Cantidad = new JFormattedTextField (amountFormat);
        JFormattedTextField jF_Precio = new JFormattedTextField (amountFormat);
        JFormattedTextField jF_IVA = new JFormattedTextField (amountFormat);
        JFormattedTextField jF_Total = new JFormattedTextField (amountFormat);*/

        jT_Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }

        });
        jT_Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jT_IVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jT_Cantidad.addFocusListener(new java.awt.event.FocusAdapter() {

            public void focusLost(java.awt.event.FocusEvent evt) {
                //this will be called on tab i.e when the field looses focus
                jTextField1ActionPerformed(evt);
            }
        });
        jT_Precio.addFocusListener(new java.awt.event.FocusAdapter() {

            public void focusLost(java.awt.event.FocusEvent evt) {
                //this will be called on tab i.e when the field looses focus
                jTextField1ActionPerformed(evt);
            }
        });
        jT_IVA.addFocusListener(new java.awt.event.FocusAdapter() {

            public void focusLost(java.awt.event.FocusEvent evt) {
                //this will be called on tab i.e when the field looses focus
                jTextField1ActionPerformed(evt);
            }
        });

    }

    JTable jtable;

    Help ayudaProducto = new Help();

    public void VinculaTabla(JTable table) {
        jtable = table;

    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {

        actualizaSumas();
    }
       private void jTextField1ActionPerformed(java.awt.event.FocusEvent evt) {

        actualizaSumas();
    }
    protected void actualizaSumas() {

        double cantidad = 0;
        if (!jT_Cantidad.getText().equalsIgnoreCase("")) {
            cantidad = Double.parseDouble(jT_Cantidad.getText());
        }
        double precio = 0;
        if (!jT_Precio.getText().equalsIgnoreCase("")) {
            precio = Double.parseDouble(jT_Precio.getText());

        }
        double iva = 0;

        if (!jT_IVA.getText().equalsIgnoreCase("")) {
            iva = Double.parseDouble(jT_IVA.getText());;
        }

        double subtotal = cantidad * precio;
        double impIVA = subtotal * iva / 100;
        double total = subtotal + impIVA;

        jT_Total.setText(Double.toString(total));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jT_Producto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jT_Cantidad = new javax.swing.JTextField();
        jT_Precio = new javax.swing.JTextField();
        jT_IVA = new javax.swing.JTextField();
        jT_Total = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        jFormattedTextField2.setText("jFormattedTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Producto");

        jLabel3.setText("Cantidad");

        jLabel4.setText("Precio");

        jLabel5.setText("IVA %");

        jLabel6.setText("Total");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jT_Cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_CantidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_CantidadFocusLost(evt);
            }
        });

        jT_Precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_PrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_PrecioFocusLost(evt);
            }
        });

        jT_IVA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_IVAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_IVAFocusLost(evt);
            }
        });

        jT_Total.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jT_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jT_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_Producto)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jT_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jT_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object[] datos = new Object[7];//creamos un object de la cantidad de COLUMNAS
        DefaultTableModel model = (DefaultTableModel) jtable.getModel();

        //datos[0] = rs.getObject(1);//cargamos la fila en el objeto
        datos[0] = ayudaProducto.getId();
        datos[1] = jT_Producto.getText();//cargamos la fila en el objeto
        datos[2] = jT_Cantidad.getText();//cargamos la fila en el objeto
        datos[3] = jT_Precio.getText();//cargamos la fila en el objeto
        datos[4] = jT_IVA.getText();//cargamos la fila en el objeto
        datos[5] = jT_Total.getText();

        model.addRow(datos);//cargamos el objeto en el model
        model.fireTableDataChanged();
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jT_CantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_CantidadFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_CantidadFocusGained

    private void jT_CantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_CantidadFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_CantidadFocusLost

    private void jT_PrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_PrecioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_PrecioFocusGained

    private void jT_PrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_PrecioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_PrecioFocusLost

    private void jT_IVAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_IVAFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_IVAFocusGained

    private void jT_IVAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_IVAFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_IVAFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Input_Items().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Input_Items.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jT_Cantidad;
    private javax.swing.JTextField jT_IVA;
    private javax.swing.JTextField jT_Precio;
    private javax.swing.JTextField jT_Producto;
    private javax.swing.JTextField jT_Total;
    // End of variables declaration//GEN-END:variables
}
