/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Outputs_New;

import Outputs.*;
import Entidades.CONSTANT;
import Entidades.Usuario;
import Inputs.Input_Clientes;
import Inputs.Input_Recorridos;
import cec.Tabla;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author martin
 */
public class Out_Vista_Recorridos extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Clientes
     */
    public Out_Vista_Recorridos() {
        initComponents();
    }

    Usuario current_user = new Usuario();

    public void setCurrent_user(Usuario user) {

        this.current_user = user;
        current_user.cargaPermisos();

    }

    public void cargaRecorridos() throws SQLException {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Recorridos = new javax.swing.JTable();
        jB_Alta_Recorridos = new javax.swing.JButton();
        jB_Modificar_Recorridos = new javax.swing.JButton();

        jT_Recorridos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Descripción", "Cobrador", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jT_Recorridos);

        jB_Alta_Recorridos.setText("Alta");
        jB_Alta_Recorridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Alta_RecorridosActionPerformed(evt);
            }
        });

        jB_Modificar_Recorridos.setText("Modificar");
        jB_Modificar_Recorridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Modificar_RecorridosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_Alta_Recorridos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB_Modificar_Recorridos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Alta_Recorridos)
                    .addComponent(jB_Modificar_Recorridos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_Modificar_RecorridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Modificar_RecorridosActionPerformed
        if(current_user.VerificoPermisos(CONSTANT.RECORRIDOS,CONSTANT.MODIFICACION)){ 
        
        }
    }//GEN-LAST:event_jB_Modificar_RecorridosActionPerformed

    private void jB_Alta_RecorridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Alta_RecorridosActionPerformed
         if(current_user.VerificoPermisos(CONSTANT.RECORRIDOS,CONSTANT.ALTA)){ 
        
         
         }
    }//GEN-LAST:event_jB_Alta_RecorridosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Alta_Recorridos;
    private javax.swing.JButton jB_Modificar_Recorridos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_Recorridos;
    // End of variables declaration//GEN-END:variables
}
