/**DOCUMENTACION DE LOS INPUTS
 * //COLOCAR ACA DETALLES DE LOGICA.
 * -EN CADA VISTA DE INPUTS TIENE QUE HABER 1 OBJETO DE LA ENTIDAD EN CUESTION
 * PARA IR CARGANDOLE LA INFORMACIÓN
 * -EL SALVADO DE LA INFO TIENE QUE ESTAR CODEADO EN LA CLASE NO EN EL INPUT
 * -EL MANEJO DE LAS CELDAS TIENE QUE ESTAR CODEADO EN EL INPUT GUARDANDO 
 * LOS DATOS EN EL OBJETO
 * 
 * 
 * 
 * 
 * CARACTERISTICAS ESPECIALES DE INPUTS:
 * //COLOCAR ACA LAS CARACTERISTICAS ESPECIFICAS QUE SE CODEEN EN ALGUN INPUT
 *
 * 
 * 
 * 
 * 
 * 
 * 
 */ 