/***DOCUMENTACION DE OUTPUTS
 * //COLOCAR DETALLES DE OUTPUT
 * -EN CADA VISTA DE OUTPUT SE UTILIZARÁ METODOS ESTATICOS DE LA CLASE EN CUESTION
 * -TODOS LAS CLASES QUE TENGAN UN OUTPUT TIENEN QUE TENER UN MÉTODO "CARGAR"
 * QUE TIENE QUE CARGAR LA TABLA A MOSTRAR
 * -LOS BOTONES DE MODIFICAR Y AGREGAR TIENEN QUE DISPARAR UN METODO DENTRO
 * DE LA CLASE TAMBIEN
 * -NINGÚN OUTPUT TIENE QUE TENER COSAS HARDCODEADAS 
 * 
 * 
 * 
 * 
 * 
 * CARACTERISTICAS ESPECIALES DE OUTPUTS:
 * //COLOCAR ACA LAS CARACTERISTICAS ESPECIFICAS QUE SE CODEEN EN ALGUN OUTPUT
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 */