/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Outputs;

import Entidades.Usuario;
import Inputs.Input_Clientes;
import Inputs.Input_Productos;
import Inputs.Input_Recorridos;
import cec.Tabla;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputMap;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author martin
 */
public class Panel_Productos extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Clientes
     */
    public Panel_Productos() {
        initComponents();
    }

    Usuario current_user = new Usuario();

    public void setCurrent_user(Usuario user) {

        this.current_user = user;
        current_user.cargaPermisos();

    }

    public void carga() throws SQLException {
        DefaultTableModel modelo = new DefaultTableModel();
        jT_Productos.setModel(modelo);
        ResultSet rs = Tabla.select("id,descripcion,precio,stock", "productos", "1=1");

        Object[] datos = new Object[4];//creamos un object de la cantidad de COLUMNAS
        modelo.addColumn("ID");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        while (rs.next()) {
            for (int i = 0; i < 4; i++) {
                datos[i] = rs.getObject(i + 1);//cargamos la fila en el objeto
            }
            modelo.addRow(datos);//cargamos el objeto en el model
        }
        modelo.fireTableDataChanged();
        rs.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Productos = new javax.swing.JTable();
        jB_Alta_Productos = new javax.swing.JButton();
        jB_Baja_Productos = new javax.swing.JButton();
        jB_Modificar_Productos = new javax.swing.JButton();

        jT_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Descripción", "Stock", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jT_Productos);

        jB_Alta_Productos.setText("Alta");
        jB_Alta_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Alta_ProductosActionPerformed(evt);
            }
        });

        jB_Baja_Productos.setText("Baja");

        jB_Modificar_Productos.setText("Modificar");
        jB_Modificar_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Modificar_ProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_Alta_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB_Baja_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB_Modificar_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Alta_Productos)
                    .addComponent(jB_Baja_Productos)
                    .addComponent(jB_Modificar_Productos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_Modificar_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Modificar_ProductosActionPerformed
        int selectedRow = jT_Productos.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jT_Productos.getModel();

        int selectedID = (int) model.getValueAt(selectedRow, 0);

        Input_Productos JframeProductos = new Input_Productos();

        try {
            JframeProductos.Modificacion(selectedID);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        JframeProductos.setVisible(true);
        JframeProductos.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jB_Modificar_ProductosActionPerformed

    private void jB_Alta_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Alta_ProductosActionPerformed
        int selectedRow = jT_Productos.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jT_Productos.getModel();

        //int selectedID = (int) model.getValueAt(selectedRow, 0);
        Input_Productos JframeProductos = new Input_Productos();

        try {
            JframeProductos.Alta();
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        JframeProductos.setVisible(true);
        JframeProductos.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jB_Alta_ProductosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Alta_Productos;
    private javax.swing.JButton jB_Baja_Productos;
    private javax.swing.JButton jB_Modificar_Productos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_Productos;
    // End of variables declaration//GEN-END:variables
}
